/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

/**
 *
 * @author miquel
 */
public class PanelMenuPrincipal extends javax.swing.JPanel {

    ControladorPresentacio cp;
    /**
     * Creates new form PanelMenuPrincipal
     */
    public PanelMenuPrincipal( ControladorPresentacio cpres ) {
        cp = cpres;
        initComponents();
        this.setBounds(0,0,700,500);
    }
    
    public void setNomUnitatDocent( String nomUD ){
        this.etiquetaNom.setText(nomUD);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        botoLogout = new javax.swing.JButton();
        etiquetaNom = new javax.swing.JLabel();

        botoLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botoLogout.setText("Logout");
        botoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoLogoutActionPerformed(evt);
            }
        });
        botoLogout.setBounds(275, 400, 150, 40);
        jLayeredPane1.add(botoLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        etiquetaNom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiquetaNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNom.setText("MIQUEL");
        etiquetaNom.setBounds(100, 50, 500, 30);
        jLayeredPane1.add(etiquetaNom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoLogoutActionPerformed
        cp.canviaPanel("login");
    }//GEN-LAST:event_botoLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoLogout;
    private javax.swing.JLabel etiquetaNom;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
