/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelVeureHoraris.java
 *
 * Created on 19-may-2013, 17:24:29
 */

package Presentacio;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author albertomarin
 */
public class PanelVeureHoraris extends javax.swing.JPanel {
    
    ControladorPresentacio cp;

    /** Creates new form PanelGeneracioAules */
    public PanelVeureHoraris(ControladorPresentacio cpr) {
        cp = cpr;
        initComponents();
        this.setBounds(0, 0, 700, 550);
    }

    public void setNomUnitatDocent(String nomUD){
        this.jLabel2.setText(nomUD);
    }
    
    public void carregaLlistaHoraris(){
        jList1.removeAll();
        ArrayList<String> llistaHoraris = cp.carregaLlistaHoraris();
        DefaultListModel listModel = new DefaultListModel();
        jList1.setModel(listModel);
        for (String h : llistaHoraris) {
            h = h.replace( ".o", "" );
            listModel.addElement(h);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        botoVeure = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botoEsborrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 550));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("seleciona'n un");
        jLabel1.setBounds(80, 110, 340, 19);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "a" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane1.setBounds(80, 160, 340, 290);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        botoVeure.setText("Veure");
        botoVeure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoVeureActionPerformed(evt);
            }
        });
        botoVeure.setBounds(500, 280, 100, 30);
        jLayeredPane1.add(botoVeure, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Tornar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(500, 180, 100, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.setBounds(80, 30, 500, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        botoEsborrar.setText("esborrar");
        botoEsborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEsborrarActionPerformed(evt);
            }
        });
        botoEsborrar.setBounds(500, 380, 100, 30);
        jLayeredPane1.add(botoEsborrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Arxius amb Horaris Disponibles:");
        jLabel3.setBounds(80, 90, 340, 19);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cp.canviaPanel("menuPrincipal");
        jList1.removeAll();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botoVeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoVeureActionPerformed
        Object[] cadena = jList1.getSelectedValues();
        int h = cadena.length;
        if (h == 0) cp.mostraAvis("Seleccioni l'horari que vol veure", "WARNING");
        else{
            String nomhorari = (String) jList1.getSelectedValue();
            cp.carregaHorari(nomhorari);
        }
    }//GEN-LAST:event_botoVeureActionPerformed

    private void botoEsborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEsborrarActionPerformed
        Object[] cadena = jList1.getSelectedValues();
        int h = cadena.length;
        if (h == 0) cp.mostraAvis("Seleccioni l'horari que vols esorrar", "WARNING");
        else{
            String nomhorari = (String) jList1.getSelectedValue();
            cp.esborraHorari(nomhorari);
        }
        carregaLlistaHoraris();
    }//GEN-LAST:event_botoEsborrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoEsborrar;
    private javax.swing.JButton botoVeure;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
