/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHorariLectiu.java
 *
 * Created on 12-may-2013, 19:11:59
 */

package Presentacio;

import java.util.ArrayList;

/**
 *
 * @author albertomarin
 */
public class PanelHorariLectiu extends javax.swing.JPanel {


    ControladorPresentacio cp;
    Casella[][] caselles; 

    /** Creates new form PanelHorariLectiu */
    public PanelHorariLectiu(ControladorPresentacio cpr) {
        cp = cpr;
        initComponents();
        this.setBounds(0, 0, 700, 550);
        
        caselles = new Casella[7][24];
        
        for(int d = 0; d < 7; ++d){ // d = 7
            for(int h = 0; h < 24; ++h){ // h = 24
                caselles[d][h] = new Casella(d, h);
                this.fondoConfHoraria.add(caselles[d][h]);
                caselles[d][h].setBounds(d*75, h*22, 75, 22);
            }
        }
        
    }
    
    
    public void carregaConfHoraria(){
        boolean b = false;
        if( cp.existeixConfiguracioHoraria() ) {
        b = true;
        for(int d = 0; d < 7; ++d){ // d = 7
            for(int h = 0; h < 24; ++h){ // h = 24
                caselles[d][h].reset();
            }
        }
        
        ArrayList<String> conf = cp.llegeixConfiguracioHoraria();
        
        String dia = "";
        for( int fila = 0; fila < conf.size(); ++fila ){
            
            String linia = conf.get(fila);
            
            if( linia.contains("dilluns") || linia.contains("dimarts") || linia.contains("dimecres")
            || linia.contains("dijous") || linia.contains("divendres") || linia.contains("dissabte") 
            || linia.contains("diumenge") ) {
                dia = linia;
            } 
            else{
                int hora = Integer.parseInt( linia );
                if( dia.contains("dilluns") ){
                    caselles[0][hora].canviaEstat();
                }
                else if( dia.contains("dimarts") ) {
                  caselles[1][hora].canviaEstat();
                }
                else if( dia.contains("dimecres") ) {
                    caselles[2][hora].canviaEstat();
                }
                else if( dia.contains("dijous") ) {
                    caselles[3][hora].canviaEstat();
                }
                else if( dia.contains("divendres") ) {
                    caselles[4][hora].canviaEstat();    
                }
                else if( dia.contains("dissabte") ) {
                    caselles[5][hora].canviaEstat();
                }
                else if ( dia.contains("diumenge")) {
                    caselles[6][hora].canviaEstat();
                }
            }
        }
        
        }
        
        boolean c = b;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayeredPrincipal = new javax.swing.JLayeredPane();
        botoTornar = new javax.swing.JButton();
        botoAcceptar = new javax.swing.JButton();
        fondoConfHoraria = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 550));

        botoTornar.setText("Tornar");
        botoTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoTornarActionPerformed(evt);
            }
        });
        botoTornar.setBounds(590, 270, 100, 40);
        LayeredPrincipal.add(botoTornar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        botoAcceptar.setText("Acceptar");
        botoAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAcceptarActionPerformed(evt);
            }
        });
        botoAcceptar.setBounds(590, 210, 100, 40);
        LayeredPrincipal.add(botoAcceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fondoConfHoraria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fondoConfHoraria.setBounds(40, 22, 525, 528);
        LayeredPrincipal.add(fondoConfHoraria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DIJOUS");
        jLabel2.setBounds(265, 0, 75, 20);
        LayeredPrincipal.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DILLUNS");
        jLabel3.setBounds(40, 0, 75, 20);
        LayeredPrincipal.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DIMARTS");
        jLabel4.setBounds(115, 0, 75, 20);
        LayeredPrincipal.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DIMECRES");
        jLabel5.setBounds(190, 0, 75, 20);
        LayeredPrincipal.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DISSABTE");
        jLabel6.setBounds(420, 0, 75, 20);
        LayeredPrincipal.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DIVENDRES");
        jLabel7.setBounds(340, 0, 80, 20);
        LayeredPrincipal.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DIUMENGE");
        jLabel8.setBounds(500, 0, 75, 20);
        LayeredPrincipal.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("1");
        jLabel9.setBounds(0, 42, 40, 22);
        LayeredPrincipal.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("0");
        jLabel10.setBounds(0, 20, 40, 22);
        LayeredPrincipal.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("2");
        jLabel11.setBounds(0, 64, 40, 22);
        LayeredPrincipal.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel11.getAccessibleContext().setAccessibleDescription("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("3");
        jLabel12.setBounds(0, 86, 40, 22);
        LayeredPrincipal.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("4");
        jLabel13.setBounds(0, 108, 40, 22);
        LayeredPrincipal.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("5");
        jLabel14.setBounds(0, 130, 40, 22);
        LayeredPrincipal.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("6");
        jLabel15.setBounds(0, 152, 40, 22);
        LayeredPrincipal.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("7");
        jLabel16.setBounds(0, 174, 40, 22);
        LayeredPrincipal.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("8");
        jLabel17.setBounds(0, 196, 40, 22);
        LayeredPrincipal.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("9");
        jLabel18.setBounds(0, 218, 40, 22);
        LayeredPrincipal.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("10");
        jLabel19.setBounds(0, 240, 40, 22);
        LayeredPrincipal.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("11");
        jLabel20.setBounds(0, 262, 40, 22);
        LayeredPrincipal.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("12");
        jLabel21.setBounds(0, 284, 40, 22);
        LayeredPrincipal.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("13");
        jLabel22.setBounds(0, 306, 40, 22);
        LayeredPrincipal.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("14");
        jLabel23.setBounds(0, 328, 40, 22);
        LayeredPrincipal.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("15");
        jLabel24.setBounds(0, 350, 40, 22);
        LayeredPrincipal.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("16");
        jLabel25.setBounds(0, 372, 40, 22);
        LayeredPrincipal.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("17");
        jLabel26.setBounds(0, 394, 40, 22);
        LayeredPrincipal.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("18");
        jLabel27.setBounds(0, 416, 40, 22);
        LayeredPrincipal.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("19");
        jLabel28.setBounds(0, 438, 40, 22);
        LayeredPrincipal.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("20");
        jLabel29.setBounds(0, 460, 40, 22);
        LayeredPrincipal.add(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("21");
        jLabel30.setBounds(0, 482, 40, 22);
        LayeredPrincipal.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("22");
        jLabel31.setBounds(0, 504, 40, 22);
        LayeredPrincipal.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("23");
        jLabel32.setBounds(0, 526, 40, 22);
        LayeredPrincipal.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayeredPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayeredPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botoTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoTornarActionPerformed
        cp.canviaPanel("menuPrincipal");
    }//GEN-LAST:event_botoTornarActionPerformed

    private void botoAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAcceptarActionPerformed
        ArrayList conf = new ArrayList();
        for(int d = 0; d < 7; ++d){
            if(d == 0) conf.add("dilluns");
            else if( d == 1) conf.add("dimarts");
            else if( d == 2) conf.add("dimecres");
            else if( d == 3) conf.add("dijous");
            else if( d == 4) conf.add("divendres");
            else if( d == 5) conf.add("dissabte");
            else if( d == 6) conf.add("diumenge");
            for(int h = 0 ; h < 24; ++h ) {
                if( caselles[d][h].getEstat() ){
                    conf.add(h);
                }
            }
        }
        cp.guardaConfiguracioHoraria( conf );
        cp.canviaPanel("PanelGeneracioAssignatures");
    }//GEN-LAST:event_botoAcceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredPrincipal;
    private javax.swing.JButton botoAcceptar;
    private javax.swing.JButton botoTornar;
    private javax.swing.JLayeredPane fondoConfHoraria;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables


}
