/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHorariLectiu.java
 *
 * Created on 12-may-2013, 19:11:59
 */

package Presentacio;

/**
 *
 * @author albertomarin
 */
public class PanelHorariLectiu extends javax.swing.JPanel {


    ControladorPresentacio cp;

    /** Creates new form PanelHorariLectiu */
    public PanelHorariLectiu(ControladorPresentacio cpr) {
        cp = cpr;
        initComponents();
        this.setBounds(0, 0, 700, 500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox76 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox79 = new javax.swing.JCheckBox();
        jCheckBox80 = new javax.swing.JCheckBox();
        jCheckBox81 = new javax.swing.JCheckBox();
        jCheckBox82 = new javax.swing.JCheckBox();
        jCheckBox83 = new javax.swing.JCheckBox();
        jCheckBox84 = new javax.swing.JCheckBox();
        jCheckBox85 = new javax.swing.JCheckBox();
        jCheckBox86 = new javax.swing.JCheckBox();
        jCheckBox87 = new javax.swing.JCheckBox();
        jCheckBox88 = new javax.swing.JCheckBox();
        jCheckBox89 = new javax.swing.JCheckBox();
        jCheckBox90 = new javax.swing.JCheckBox();
        jCheckBox91 = new javax.swing.JCheckBox();
        jCheckBox92 = new javax.swing.JCheckBox();
        jCheckBox93 = new javax.swing.JCheckBox();
        jCheckBox94 = new javax.swing.JCheckBox();
        jCheckBox95 = new javax.swing.JCheckBox();
        jCheckBox96 = new javax.swing.JCheckBox();
        jCheckBox97 = new javax.swing.JCheckBox();
        jCheckBox98 = new javax.swing.JCheckBox();
        jCheckBox99 = new javax.swing.JCheckBox();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox101 = new javax.swing.JCheckBox();
        jCheckBox102 = new javax.swing.JCheckBox();
        jCheckBox103 = new javax.swing.JCheckBox();
        jCheckBox104 = new javax.swing.JCheckBox();
        jCheckBox105 = new javax.swing.JCheckBox();
        jCheckBox106 = new javax.swing.JCheckBox();
        jCheckBox107 = new javax.swing.JCheckBox();
        jCheckBox108 = new javax.swing.JCheckBox();
        jCheckBox109 = new javax.swing.JCheckBox();
        jCheckBox110 = new javax.swing.JCheckBox();
        jCheckBox111 = new javax.swing.JCheckBox();
        jCheckBox112 = new javax.swing.JCheckBox();
        jCheckBox113 = new javax.swing.JCheckBox();
        jCheckBox114 = new javax.swing.JCheckBox();
        jCheckBox115 = new javax.swing.JCheckBox();
        jCheckBox116 = new javax.swing.JCheckBox();
        jCheckBox117 = new javax.swing.JCheckBox();
        jCheckBox118 = new javax.swing.JCheckBox();
        jCheckBox119 = new javax.swing.JCheckBox();
        jCheckBox120 = new javax.swing.JCheckBox();
        jCheckBox121 = new javax.swing.JCheckBox();
        jCheckBox122 = new javax.swing.JCheckBox();
        jCheckBox123 = new javax.swing.JCheckBox();
        jCheckBox124 = new javax.swing.JCheckBox();
        jCheckBox125 = new javax.swing.JCheckBox();
        jCheckBox126 = new javax.swing.JCheckBox();
        jCheckBox127 = new javax.swing.JCheckBox();
        jCheckBox128 = new javax.swing.JCheckBox();
        jCheckBox129 = new javax.swing.JCheckBox();
        jCheckBox130 = new javax.swing.JCheckBox();
        jCheckBox131 = new javax.swing.JCheckBox();
        jCheckBox132 = new javax.swing.JCheckBox();
        jCheckBox133 = new javax.swing.JCheckBox();
        jCheckBox134 = new javax.swing.JCheckBox();
        jCheckBox135 = new javax.swing.JCheckBox();
        jCheckBox136 = new javax.swing.JCheckBox();
        jCheckBox137 = new javax.swing.JCheckBox();
        jCheckBox138 = new javax.swing.JCheckBox();
        jCheckBox139 = new javax.swing.JCheckBox();
        jCheckBox140 = new javax.swing.JCheckBox();
        jCheckBox141 = new javax.swing.JCheckBox();
        jCheckBox142 = new javax.swing.JCheckBox();
        jCheckBox143 = new javax.swing.JCheckBox();
        jCheckBox144 = new javax.swing.JCheckBox();
        jCheckBox145 = new javax.swing.JCheckBox();
        jCheckBox146 = new javax.swing.JCheckBox();
        jCheckBox147 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(460, 500));

        jLabel1.setText("Seleccioni el seu horari lectiu:");
        jLabel1.setBounds(30, 0, 213, 15);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Lun      Mar      Mie      Jue      Vie      Sab      Dom");
        jLabel2.setBounds(70, 20, 390, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("<html>00:00<br>\n01:00<br>\n02:00<br>\n03:00<br>\n04:00<br>\n05:00<br>\n06:00<br>\n07:00<br>\n08:00<br>\n09:00<br>\n10:00<br>\n11:00<br>\n12:00<br>\n13:00<br>\n14:00<br>\n15:00<br>\n16:00<br>\n17:00<br>\n18:00<br>\n19:00<br>\n20:00<br>\n21:00<br>\n22:00<br>\n23:00<br>\n</html>");
        jLabel3.setBounds(10, 40, 41, 450);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Cancel·la");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(480, 410, 100, 25);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox1.setBounds(430, 50, 30, 21);
        jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox2.setBounds(70, 50, 30, 21);
        jLayeredPane1.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox3.setBounds(130, 50, 30, 21);
        jLayeredPane1.add(jCheckBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox4.setBounds(190, 50, 30, 21);
        jLayeredPane1.add(jCheckBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox5.setBounds(250, 50, 30, 21);
        jLayeredPane1.add(jCheckBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox6.setBounds(310, 50, 30, 21);
        jLayeredPane1.add(jCheckBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox7.setBounds(370, 50, 30, 21);
        jLayeredPane1.add(jCheckBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox8.setBounds(430, 70, 30, 21);
        jLayeredPane1.add(jCheckBox8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox9.setBounds(70, 70, 30, 21);
        jLayeredPane1.add(jCheckBox9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox10.setBounds(130, 70, 30, 21);
        jLayeredPane1.add(jCheckBox10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox11.setBounds(190, 70, 30, 21);
        jLayeredPane1.add(jCheckBox11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox12.setBounds(250, 70, 30, 21);
        jLayeredPane1.add(jCheckBox12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox13.setBounds(310, 70, 30, 21);
        jLayeredPane1.add(jCheckBox13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox14.setBounds(370, 70, 30, 21);
        jLayeredPane1.add(jCheckBox14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox15.setBounds(430, 90, 30, 21);
        jLayeredPane1.add(jCheckBox15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox16.setBounds(70, 90, 30, 21);
        jLayeredPane1.add(jCheckBox16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox17.setBounds(130, 90, 30, 21);
        jLayeredPane1.add(jCheckBox17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox18.setBounds(190, 90, 30, 21);
        jLayeredPane1.add(jCheckBox18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox19.setBounds(250, 90, 30, 21);
        jLayeredPane1.add(jCheckBox19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox20.setBounds(310, 90, 30, 21);
        jLayeredPane1.add(jCheckBox20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox21.setBounds(370, 90, 30, 21);
        jLayeredPane1.add(jCheckBox21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox22.setBounds(430, 110, 30, 21);
        jLayeredPane1.add(jCheckBox22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox23.setBounds(70, 110, 30, 21);
        jLayeredPane1.add(jCheckBox23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox24.setBounds(130, 110, 30, 21);
        jLayeredPane1.add(jCheckBox24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox25.setBounds(190, 110, 30, 21);
        jLayeredPane1.add(jCheckBox25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox26.setBounds(250, 110, 30, 21);
        jLayeredPane1.add(jCheckBox26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox27.setBounds(310, 110, 30, 21);
        jLayeredPane1.add(jCheckBox27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox28.setBounds(370, 110, 30, 21);
        jLayeredPane1.add(jCheckBox28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox29.setBounds(430, 130, 30, 21);
        jLayeredPane1.add(jCheckBox29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox30.setBounds(70, 130, 30, 21);
        jLayeredPane1.add(jCheckBox30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox31.setBounds(130, 130, 30, 21);
        jLayeredPane1.add(jCheckBox31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox32.setBounds(190, 130, 30, 21);
        jLayeredPane1.add(jCheckBox32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox33.setBounds(250, 130, 30, 21);
        jLayeredPane1.add(jCheckBox33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox34.setBounds(310, 130, 30, 21);
        jLayeredPane1.add(jCheckBox34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox35.setBounds(370, 130, 30, 21);
        jLayeredPane1.add(jCheckBox35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox36.setBounds(430, 150, 30, 21);
        jLayeredPane1.add(jCheckBox36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox37.setBounds(70, 150, 30, 21);
        jLayeredPane1.add(jCheckBox37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox38.setBounds(130, 150, 30, 21);
        jLayeredPane1.add(jCheckBox38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox39.setBounds(190, 150, 30, 21);
        jLayeredPane1.add(jCheckBox39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox40.setBounds(250, 150, 30, 21);
        jLayeredPane1.add(jCheckBox40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox41.setBounds(310, 150, 30, 21);
        jLayeredPane1.add(jCheckBox41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox42.setBounds(370, 150, 30, 21);
        jLayeredPane1.add(jCheckBox42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox43.setBounds(430, 170, 30, 21);
        jLayeredPane1.add(jCheckBox43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox44.setBounds(70, 170, 30, 21);
        jLayeredPane1.add(jCheckBox44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox45.setBounds(130, 170, 30, 21);
        jLayeredPane1.add(jCheckBox45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox46.setBounds(190, 170, 30, 21);
        jLayeredPane1.add(jCheckBox46, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox47.setBounds(250, 170, 30, 21);
        jLayeredPane1.add(jCheckBox47, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox48.setBounds(310, 170, 30, 21);
        jLayeredPane1.add(jCheckBox48, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox49.setBounds(370, 170, 30, 21);
        jLayeredPane1.add(jCheckBox49, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox50.setBounds(430, 190, 30, 21);
        jLayeredPane1.add(jCheckBox50, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox51.setBounds(70, 190, 30, 21);
        jLayeredPane1.add(jCheckBox51, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox52.setBounds(130, 190, 30, 21);
        jLayeredPane1.add(jCheckBox52, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox53.setBounds(190, 190, 30, 21);
        jLayeredPane1.add(jCheckBox53, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox54.setBounds(250, 190, 30, 21);
        jLayeredPane1.add(jCheckBox54, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox55.setBounds(310, 190, 30, 21);
        jLayeredPane1.add(jCheckBox55, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox56.setBounds(370, 190, 30, 21);
        jLayeredPane1.add(jCheckBox56, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox57.setBounds(430, 210, 30, 21);
        jLayeredPane1.add(jCheckBox57, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox58.setBounds(70, 210, 30, 21);
        jLayeredPane1.add(jCheckBox58, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox59.setBounds(130, 210, 30, 21);
        jLayeredPane1.add(jCheckBox59, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox60.setBounds(190, 210, 30, 21);
        jLayeredPane1.add(jCheckBox60, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox61.setBounds(250, 210, 30, 21);
        jLayeredPane1.add(jCheckBox61, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox62.setBounds(310, 210, 30, 21);
        jLayeredPane1.add(jCheckBox62, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox63.setBounds(370, 210, 30, 21);
        jLayeredPane1.add(jCheckBox63, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox64.setBounds(430, 230, 30, 21);
        jLayeredPane1.add(jCheckBox64, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox65.setBounds(70, 230, 30, 21);
        jLayeredPane1.add(jCheckBox65, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox66.setBounds(130, 230, 30, 21);
        jLayeredPane1.add(jCheckBox66, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox67.setBounds(190, 230, 30, 21);
        jLayeredPane1.add(jCheckBox67, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox68.setBounds(250, 230, 30, 21);
        jLayeredPane1.add(jCheckBox68, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox69.setBounds(310, 230, 30, 21);
        jLayeredPane1.add(jCheckBox69, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox70.setBounds(370, 230, 30, 21);
        jLayeredPane1.add(jCheckBox70, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox71.setBounds(430, 250, 30, 21);
        jLayeredPane1.add(jCheckBox71, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox72.setBounds(70, 250, 30, 21);
        jLayeredPane1.add(jCheckBox72, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox73.setBounds(130, 250, 30, 21);
        jLayeredPane1.add(jCheckBox73, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox74.setBounds(190, 250, 30, 21);
        jLayeredPane1.add(jCheckBox74, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox75.setBounds(250, 250, 30, 21);
        jLayeredPane1.add(jCheckBox75, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox76.setBounds(310, 250, 30, 21);
        jLayeredPane1.add(jCheckBox76, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox77.setBounds(370, 250, 30, 21);
        jLayeredPane1.add(jCheckBox77, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox78.setBounds(430, 270, 30, 21);
        jLayeredPane1.add(jCheckBox78, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox79.setBounds(70, 270, 30, 21);
        jLayeredPane1.add(jCheckBox79, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox80.setBounds(130, 270, 30, 21);
        jLayeredPane1.add(jCheckBox80, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox81.setBounds(190, 270, 30, 21);
        jLayeredPane1.add(jCheckBox81, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox82.setBounds(250, 270, 30, 21);
        jLayeredPane1.add(jCheckBox82, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox83.setBounds(310, 270, 30, 21);
        jLayeredPane1.add(jCheckBox83, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox84.setBounds(370, 270, 30, 21);
        jLayeredPane1.add(jCheckBox84, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox85.setBounds(430, 290, 30, 21);
        jLayeredPane1.add(jCheckBox85, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox86.setBounds(70, 290, 30, 21);
        jLayeredPane1.add(jCheckBox86, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox87.setBounds(130, 290, 30, 21);
        jLayeredPane1.add(jCheckBox87, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox88.setBounds(190, 290, 30, 21);
        jLayeredPane1.add(jCheckBox88, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox89.setBounds(250, 290, 30, 21);
        jLayeredPane1.add(jCheckBox89, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox90.setBounds(310, 290, 30, 21);
        jLayeredPane1.add(jCheckBox90, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox91.setBounds(370, 290, 30, 21);
        jLayeredPane1.add(jCheckBox91, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox92.setBounds(430, 310, 30, 21);
        jLayeredPane1.add(jCheckBox92, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox93.setBounds(70, 310, 30, 21);
        jLayeredPane1.add(jCheckBox93, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox94.setBounds(130, 310, 30, 21);
        jLayeredPane1.add(jCheckBox94, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox95.setBounds(190, 310, 30, 21);
        jLayeredPane1.add(jCheckBox95, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox96.setBounds(250, 310, 30, 21);
        jLayeredPane1.add(jCheckBox96, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox97.setBounds(310, 310, 30, 21);
        jLayeredPane1.add(jCheckBox97, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox98.setBounds(370, 310, 30, 21);
        jLayeredPane1.add(jCheckBox98, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox99.setBounds(430, 330, 30, 21);
        jLayeredPane1.add(jCheckBox99, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox100.setBounds(70, 330, 30, 21);
        jLayeredPane1.add(jCheckBox100, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox101.setBounds(130, 330, 30, 21);
        jLayeredPane1.add(jCheckBox101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox102.setBounds(190, 330, 30, 21);
        jLayeredPane1.add(jCheckBox102, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox103.setBounds(250, 330, 30, 21);
        jLayeredPane1.add(jCheckBox103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox104.setBounds(310, 330, 30, 21);
        jLayeredPane1.add(jCheckBox104, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox105.setBounds(370, 330, 30, 21);
        jLayeredPane1.add(jCheckBox105, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox106.setBounds(430, 350, 30, 21);
        jLayeredPane1.add(jCheckBox106, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox107.setBounds(70, 350, 30, 21);
        jLayeredPane1.add(jCheckBox107, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox108.setBounds(130, 350, 30, 21);
        jLayeredPane1.add(jCheckBox108, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox109.setBounds(190, 350, 30, 21);
        jLayeredPane1.add(jCheckBox109, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox110.setBounds(250, 350, 30, 21);
        jLayeredPane1.add(jCheckBox110, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox111.setBounds(310, 350, 30, 21);
        jLayeredPane1.add(jCheckBox111, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox112.setBounds(370, 350, 30, 21);
        jLayeredPane1.add(jCheckBox112, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox113.setBounds(430, 370, 30, 21);
        jLayeredPane1.add(jCheckBox113, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox114.setBounds(70, 370, 30, 21);
        jLayeredPane1.add(jCheckBox114, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox115.setBounds(130, 370, 30, 21);
        jLayeredPane1.add(jCheckBox115, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox116.setBounds(190, 370, 30, 21);
        jLayeredPane1.add(jCheckBox116, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox117.setBounds(250, 370, 30, 21);
        jLayeredPane1.add(jCheckBox117, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox118.setBounds(310, 370, 30, 21);
        jLayeredPane1.add(jCheckBox118, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox119.setBounds(370, 370, 30, 21);
        jLayeredPane1.add(jCheckBox119, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox120.setBounds(430, 390, 30, 21);
        jLayeredPane1.add(jCheckBox120, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox121.setBounds(70, 390, 30, 21);
        jLayeredPane1.add(jCheckBox121, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox122.setBounds(130, 390, 30, 21);
        jLayeredPane1.add(jCheckBox122, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox123.setBounds(190, 390, 30, 21);
        jLayeredPane1.add(jCheckBox123, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox124.setBounds(250, 390, 30, 21);
        jLayeredPane1.add(jCheckBox124, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox125.setBounds(310, 390, 30, 21);
        jLayeredPane1.add(jCheckBox125, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox126.setBounds(370, 390, 30, 21);
        jLayeredPane1.add(jCheckBox126, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox127.setBounds(430, 410, 30, 21);
        jLayeredPane1.add(jCheckBox127, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox128.setBounds(70, 410, 30, 21);
        jLayeredPane1.add(jCheckBox128, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox129.setBounds(130, 410, 30, 21);
        jLayeredPane1.add(jCheckBox129, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox130.setBounds(190, 410, 30, 21);
        jLayeredPane1.add(jCheckBox130, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox131.setBounds(250, 410, 30, 21);
        jLayeredPane1.add(jCheckBox131, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox132.setBounds(310, 410, 30, 21);
        jLayeredPane1.add(jCheckBox132, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox133.setBounds(370, 410, 30, 21);
        jLayeredPane1.add(jCheckBox133, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox134.setBounds(430, 430, 30, 21);
        jLayeredPane1.add(jCheckBox134, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox135.setBounds(70, 430, 30, 21);
        jLayeredPane1.add(jCheckBox135, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox136.setBounds(130, 430, 30, 21);
        jLayeredPane1.add(jCheckBox136, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox137.setBounds(190, 430, 30, 21);
        jLayeredPane1.add(jCheckBox137, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox138.setBounds(250, 430, 30, 21);
        jLayeredPane1.add(jCheckBox138, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox139.setBounds(310, 430, 30, 21);
        jLayeredPane1.add(jCheckBox139, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox140.setBounds(370, 430, 30, 21);
        jLayeredPane1.add(jCheckBox140, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox141.setBounds(430, 450, 30, 21);
        jLayeredPane1.add(jCheckBox141, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox142.setBounds(70, 450, 30, 21);
        jLayeredPane1.add(jCheckBox142, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox143.setBounds(130, 450, 30, 21);
        jLayeredPane1.add(jCheckBox143, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox144.setBounds(190, 450, 30, 21);
        jLayeredPane1.add(jCheckBox144, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox145.setBounds(250, 450, 30, 21);
        jLayeredPane1.add(jCheckBox145, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox146.setBounds(310, 450, 30, 21);
        jLayeredPane1.add(jCheckBox146, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox147.setBounds(370, 450, 30, 21);
        jLayeredPane1.add(jCheckBox147, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Següent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(480, 440, 100, 25);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cp.canviaPanel("menuPrincipal");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox100;
    private javax.swing.JCheckBox jCheckBox101;
    private javax.swing.JCheckBox jCheckBox102;
    private javax.swing.JCheckBox jCheckBox103;
    private javax.swing.JCheckBox jCheckBox104;
    private javax.swing.JCheckBox jCheckBox105;
    private javax.swing.JCheckBox jCheckBox106;
    private javax.swing.JCheckBox jCheckBox107;
    private javax.swing.JCheckBox jCheckBox108;
    private javax.swing.JCheckBox jCheckBox109;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox110;
    private javax.swing.JCheckBox jCheckBox111;
    private javax.swing.JCheckBox jCheckBox112;
    private javax.swing.JCheckBox jCheckBox113;
    private javax.swing.JCheckBox jCheckBox114;
    private javax.swing.JCheckBox jCheckBox115;
    private javax.swing.JCheckBox jCheckBox116;
    private javax.swing.JCheckBox jCheckBox117;
    private javax.swing.JCheckBox jCheckBox118;
    private javax.swing.JCheckBox jCheckBox119;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox120;
    private javax.swing.JCheckBox jCheckBox121;
    private javax.swing.JCheckBox jCheckBox122;
    private javax.swing.JCheckBox jCheckBox123;
    private javax.swing.JCheckBox jCheckBox124;
    private javax.swing.JCheckBox jCheckBox125;
    private javax.swing.JCheckBox jCheckBox126;
    private javax.swing.JCheckBox jCheckBox127;
    private javax.swing.JCheckBox jCheckBox128;
    private javax.swing.JCheckBox jCheckBox129;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox130;
    private javax.swing.JCheckBox jCheckBox131;
    private javax.swing.JCheckBox jCheckBox132;
    private javax.swing.JCheckBox jCheckBox133;
    private javax.swing.JCheckBox jCheckBox134;
    private javax.swing.JCheckBox jCheckBox135;
    private javax.swing.JCheckBox jCheckBox136;
    private javax.swing.JCheckBox jCheckBox137;
    private javax.swing.JCheckBox jCheckBox138;
    private javax.swing.JCheckBox jCheckBox139;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox140;
    private javax.swing.JCheckBox jCheckBox141;
    private javax.swing.JCheckBox jCheckBox142;
    private javax.swing.JCheckBox jCheckBox143;
    private javax.swing.JCheckBox jCheckBox144;
    private javax.swing.JCheckBox jCheckBox145;
    private javax.swing.JCheckBox jCheckBox146;
    private javax.swing.JCheckBox jCheckBox147;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox63;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox80;
    private javax.swing.JCheckBox jCheckBox81;
    private javax.swing.JCheckBox jCheckBox82;
    private javax.swing.JCheckBox jCheckBox83;
    private javax.swing.JCheckBox jCheckBox84;
    private javax.swing.JCheckBox jCheckBox85;
    private javax.swing.JCheckBox jCheckBox86;
    private javax.swing.JCheckBox jCheckBox87;
    private javax.swing.JCheckBox jCheckBox88;
    private javax.swing.JCheckBox jCheckBox89;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBox jCheckBox90;
    private javax.swing.JCheckBox jCheckBox91;
    private javax.swing.JCheckBox jCheckBox92;
    private javax.swing.JCheckBox jCheckBox93;
    private javax.swing.JCheckBox jCheckBox94;
    private javax.swing.JCheckBox jCheckBox95;
    private javax.swing.JCheckBox jCheckBox96;
    private javax.swing.JCheckBox jCheckBox97;
    private javax.swing.JCheckBox jCheckBox98;
    private javax.swing.JCheckBox jCheckBox99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

}
